package com.newer.datang.data.entity;

import java.math.BigDecimal;
import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class TTask {
	
	TEmployee mp_emp;
	TEmployee as_emp;
	
    public TEmployee getMp_emp() {
		return mp_emp;
	}

	public void setMp_emp(TEmployee mp_emp) {
		this.mp_emp = mp_emp;
	}

	public TEmployee getAs_emp() {
		return as_emp;
	}

	public void setAs_emp(TEmployee as_emp) {
		this.as_emp = as_emp;
	}

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.TASK_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    private BigDecimal taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.TASK_NAME
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    private String taskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.BEGIN_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date beginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.END_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.REAL_BEGIN_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date realBeginDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.REAL_END_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    @DateTimeFormat(pattern="yyyy-MM-dd")
    private Date realEndDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.STATUS
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.IMPLEMENTOR_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    private BigDecimal implementorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.ASSIGNER_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    private BigDecimal assignerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column T_TASK.TASK_DESC
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    private String taskDesc;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.TASK_ID
     *
     * @return the value of T_TASK.TASK_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public BigDecimal getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.TASK_ID
     *
     * @param taskId the value for T_TASK.TASK_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setTaskId(BigDecimal taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.TASK_NAME
     *
     * @return the value of T_TASK.TASK_NAME
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.TASK_NAME
     *
     * @param taskName the value for T_TASK.TASK_NAME
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.BEGIN_DATE
     *
     * @return the value of T_TASK.BEGIN_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public Date getBeginDate() {
        return beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.BEGIN_DATE
     *
     * @param beginDate the value for T_TASK.BEGIN_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.END_DATE
     *
     * @return the value of T_TASK.END_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.END_DATE
     *
     * @param endDate the value for T_TASK.END_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.REAL_BEGIN_DATE
     *
     * @return the value of T_TASK.REAL_BEGIN_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public Date getRealBeginDate() {
        return realBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.REAL_BEGIN_DATE
     *
     * @param realBeginDate the value for T_TASK.REAL_BEGIN_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setRealBeginDate(Date realBeginDate) {
        this.realBeginDate = realBeginDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.REAL_END_DATE
     *
     * @return the value of T_TASK.REAL_END_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public Date getRealEndDate() {
        return realEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.REAL_END_DATE
     *
     * @param realEndDate the value for T_TASK.REAL_END_DATE
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setRealEndDate(Date realEndDate) {
        this.realEndDate = realEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.STATUS
     *
     * @return the value of T_TASK.STATUS
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.STATUS
     *
     * @param status the value for T_TASK.STATUS
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.IMPLEMENTOR_ID
     *
     * @return the value of T_TASK.IMPLEMENTOR_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public BigDecimal getImplementorId() {
        return implementorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.IMPLEMENTOR_ID
     *
     * @param implementorId the value for T_TASK.IMPLEMENTOR_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setImplementorId(BigDecimal implementorId) {
        this.implementorId = implementorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.ASSIGNER_ID
     *
     * @return the value of T_TASK.ASSIGNER_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public BigDecimal getAssignerId() {
        return assignerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.ASSIGNER_ID
     *
     * @param assignerId the value for T_TASK.ASSIGNER_ID
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setAssignerId(BigDecimal assignerId) {
        this.assignerId = assignerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column T_TASK.TASK_DESC
     *
     * @return the value of T_TASK.TASK_DESC
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public String getTaskDesc() {
        return taskDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column T_TASK.TASK_DESC
     *
     * @param taskDesc the value for T_TASK.TASK_DESC
     *
     * @mbggenerated Wed Jul 08 19:18:37 CST 2020
     */
    public void setTaskDesc(String taskDesc) {
        this.taskDesc = taskDesc == null ? null : taskDesc.trim();
    }

	@Override
	public String toString() {
		return "TTask [mp_emp=" + mp_emp + ", as_emp=" + as_emp + ", taskId="
				+ taskId + ", taskName=" + taskName + ", beginDate="
				+ beginDate + ", endDate=" + endDate + ", realBeginDate="
				+ realBeginDate + ", realEndDate=" + realEndDate + ", status="
				+ status + ", implementorId=" + implementorId + ", assignerId="
				+ assignerId + ", taskDesc=" + taskDesc + "]";
	}
    
    
}