package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.Affiche;
import com.newer.hysc.data.entity.AfficheExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AfficheMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int countByExample(AfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int deleteByExample(AfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int insert(Affiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int insertSelective(Affiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    List<Affiche> selectByExample(AfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    Affiche selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int updateByExampleSelective(@Param("record") Affiche record, @Param("example") AfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int updateByExample(@Param("record") Affiche record, @Param("example") AfficheExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int updateByPrimaryKeySelective(Affiche record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AFFICHE
     *
     * @mbggenerated Tue Jul 07 18:45:14 CST 2020
     */
    int updateByPrimaryKey(Affiche record);
}