package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.AuAuthority;
import com.newer.hysc.data.entity.AuAuthorityExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuAuthorityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int countByExample(AuAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int deleteByExample(AuAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int insert(AuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int insertSelective(AuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    List<AuAuthority> selectByExample(AuAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    AuAuthority selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int updateByExampleSelective(@Param("record") AuAuthority record, @Param("example") AuAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int updateByExample(@Param("record") AuAuthority record, @Param("example") AuAuthorityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int updateByPrimaryKeySelective(AuAuthority record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_AUTHORITY
     *
     * @mbggenerated Tue Jul 07 18:45:27 CST 2020
     */
    int updateByPrimaryKey(AuAuthority record);
}