package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.AuRole;
import com.newer.hysc.data.entity.AuRoleExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AuRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int countByExample(AuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int deleteByExample(AuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int insert(AuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int insertSelective(AuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    List<AuRole> selectByExample(AuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    AuRole selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") AuRole record, @Param("example") AuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int updateByExample(@Param("record") AuRole record, @Param("example") AuRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int updateByPrimaryKeySelective(AuRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AU_ROLE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    int updateByPrimaryKey(AuRole record);
}