package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.BasicsParameter;
import com.newer.hysc.data.entity.BasicsParameterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BasicsParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int countByExample(BasicsParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int deleteByExample(BasicsParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int insert(BasicsParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int insertSelective(BasicsParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    List<BasicsParameter> selectByExample(BasicsParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    BasicsParameter selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") BasicsParameter record, @Param("example") BasicsParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int updateByExample(@Param("record") BasicsParameter record, @Param("example") BasicsParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int updateByPrimaryKeySelective(BasicsParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BASICS_PARAMETER
     *
     * @mbggenerated Tue Jul 07 18:34:46 CST 2020
     */
    int updateByPrimaryKey(BasicsParameter record);
}