package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.DataDictionary;
import com.newer.hysc.data.entity.DataDictionaryExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DataDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int countByExample(DataDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int deleteByExample(DataDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int insert(DataDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int insertSelective(DataDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    List<DataDictionary> selectByExample(DataDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    DataDictionary selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") DataDictionary record, @Param("example") DataDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int updateByExample(@Param("record") DataDictionary record, @Param("example") DataDictionaryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int updateByPrimaryKeySelective(DataDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DATA_DICTIONARY
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    int updateByPrimaryKey(DataDictionary record);
}