package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.GoodsInfo;
import com.newer.hysc.data.entity.GoodsInfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GoodsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int countByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int deleteByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int insert(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int insertSelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    List<GoodsInfo> selectByExample(GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    GoodsInfo selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int updateByExample(@Param("record") GoodsInfo record, @Param("example") GoodsInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int updateByPrimaryKeySelective(GoodsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOODS_INFO
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    int updateByPrimaryKey(GoodsInfo record);
}