package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.InfoAnnexes;
import com.newer.hysc.data.entity.InfoAnnexesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface InfoAnnexesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int countByExample(InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int deleteByExample(InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int insert(InfoAnnexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int insertSelective(InfoAnnexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    List<InfoAnnexes> selectByExample(InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    InfoAnnexes selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int updateByExampleSelective(@Param("record") InfoAnnexes record, @Param("example") InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int updateByExample(@Param("record") InfoAnnexes record, @Param("example") InfoAnnexesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int updateByPrimaryKeySelective(InfoAnnexes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INFO_ANNEXES
     *
     * @mbggenerated Tue Jul 07 18:35:37 CST 2020
     */
    int updateByPrimaryKey(InfoAnnexes record);
}