package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.OrderList;
import com.newer.hysc.data.entity.OrderListExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int countByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int deleteByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int deleteByPrimaryKey(String listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int insert(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int insertSelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    List<OrderList> selectByExample(OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    OrderList selectByPrimaryKey(String listId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int updateByExample(@Param("record") OrderList record, @Param("example") OrderListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int updateByPrimaryKeySelective(OrderList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDER_LIST
     *
     * @mbggenerated Tue Jul 07 18:39:08 CST 2020
     */
    int updateByPrimaryKey(OrderList record);
}