package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.UserRecharge;
import com.newer.hysc.data.entity.UserRechargeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserRechargeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int countByExample(UserRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int deleteByExample(UserRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int deleteByPrimaryKey(String rechargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int insert(UserRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int insertSelective(UserRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    List<UserRecharge> selectByExample(UserRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    UserRecharge selectByPrimaryKey(String rechargeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserRecharge record, @Param("example") UserRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int updateByExample(@Param("record") UserRecharge record, @Param("example") UserRechargeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int updateByPrimaryKeySelective(UserRecharge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_RECHARGE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    int updateByPrimaryKey(UserRecharge record);
}