package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.UserBuy;
import com.newer.hysc.data.entity.UserBuyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBuyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int countByExample(UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int deleteByExample(UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int deleteByPrimaryKey(String buyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int insert(UserBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int insertSelective(UserBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    List<UserBuy> selectByExample(UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    UserBuy selectByPrimaryKey(String buyId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserBuy record, @Param("example") UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int updateByExample(@Param("record") UserBuy record, @Param("example") UserBuyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int updateByPrimaryKeySelective(UserBuy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_BUY
     *
     * @mbggenerated Tue Jul 07 18:42:08 CST 2020
     */
    int updateByPrimaryKey(UserBuy record);
}