package com.newer.hysc.data.dao;

import com.newer.hysc.data.entity.UserAccountLog201312;
import com.newer.hysc.data.entity.UserAccountLog201312Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserAccountLog201312Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int countByExample(UserAccountLog201312Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int deleteByExample(UserAccountLog201312Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int deleteByPrimaryKey(String accountLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int insert(UserAccountLog201312 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int insertSelective(UserAccountLog201312 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    List<UserAccountLog201312> selectByExample(UserAccountLog201312Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    UserAccountLog201312 selectByPrimaryKey(String accountLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int updateByExampleSelective(@Param("record") UserAccountLog201312 record, @Param("example") UserAccountLog201312Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int updateByExample(@Param("record") UserAccountLog201312 record, @Param("example") UserAccountLog201312Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int updateByPrimaryKeySelective(UserAccountLog201312 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_ACCOUNT_LOG_201312
     *
     * @mbggenerated Tue Jul 07 18:41:48 CST 2020
     */
    int updateByPrimaryKey(UserAccountLog201312 record);
}