package com.newer.hysc.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AuRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_ROLE.ID
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_ROLE.ROLECODE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    private String rolecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_ROLE.ROLENAME
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_ROLE.CREATEDATE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_ROLE.ISSTART
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    private Long isstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_ROLE.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    private String createdby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_ROLE.ID
     *
     * @return the value of AU_ROLE.ID
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_ROLE.ID
     *
     * @param id the value for AU_ROLE.ID
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_ROLE.ROLECODE
     *
     * @return the value of AU_ROLE.ROLECODE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public String getRolecode() {
        return rolecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_ROLE.ROLECODE
     *
     * @param rolecode the value for AU_ROLE.ROLECODE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public void setRolecode(String rolecode) {
        this.rolecode = rolecode == null ? null : rolecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_ROLE.ROLENAME
     *
     * @return the value of AU_ROLE.ROLENAME
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_ROLE.ROLENAME
     *
     * @param rolename the value for AU_ROLE.ROLENAME
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_ROLE.CREATEDATE
     *
     * @return the value of AU_ROLE.CREATEDATE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_ROLE.CREATEDATE
     *
     * @param createdate the value for AU_ROLE.CREATEDATE
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_ROLE.ISSTART
     *
     * @return the value of AU_ROLE.ISSTART
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public Long getIsstart() {
        return isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_ROLE.ISSTART
     *
     * @param isstart the value for AU_ROLE.ISSTART
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public void setIsstart(Long isstart) {
        this.isstart = isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_ROLE.CREATEDBY
     *
     * @return the value of AU_ROLE.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_ROLE.CREATEDBY
     *
     * @param createdby the value for AU_ROLE.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:46:18 CST 2020
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }
}