package com.newer.hysc.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class AuUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.ID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.LOGINCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String logincode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.PASSWORD
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.PASSWORD2
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String password2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.USERNAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.SEX
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.BIRTHDAY
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private Date birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.CARDTYPE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String cardtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.CARDTYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String cardtypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.IDCARD
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.COUNTRY
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.MOBILE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.EMAIL
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.USERADDRESS
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String useraddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.POSTCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String postcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.REFERID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private BigDecimal referid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.REFERCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String refercode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.ROLEID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private BigDecimal roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.ROLENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.USERTYPE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String usertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.USERTYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String usertypename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.ISSTART
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private Long isstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.LASTUPDATE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private Date lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.LASTLOGNUMBERIME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private Date lastlognumberime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.BANKACCOUNT
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String bankaccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.BANKNAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String bankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.ACCOUNTHOLDER
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String accountholder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.IDCARDPICPATH
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String idcardpicpath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AU_USER.BANKPICPATH
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    private String bankpicpath;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.ID
     *
     * @return the value of AU_USER.ID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.ID
     *
     * @param id the value for AU_USER.ID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.LOGINCODE
     *
     * @return the value of AU_USER.LOGINCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getLogincode() {
        return logincode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.LOGINCODE
     *
     * @param logincode the value for AU_USER.LOGINCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setLogincode(String logincode) {
        this.logincode = logincode == null ? null : logincode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.PASSWORD
     *
     * @return the value of AU_USER.PASSWORD
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.PASSWORD
     *
     * @param password the value for AU_USER.PASSWORD
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.PASSWORD2
     *
     * @return the value of AU_USER.PASSWORD2
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getPassword2() {
        return password2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.PASSWORD2
     *
     * @param password2 the value for AU_USER.PASSWORD2
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setPassword2(String password2) {
        this.password2 = password2 == null ? null : password2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.USERNAME
     *
     * @return the value of AU_USER.USERNAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.USERNAME
     *
     * @param username the value for AU_USER.USERNAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.SEX
     *
     * @return the value of AU_USER.SEX
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.SEX
     *
     * @param sex the value for AU_USER.SEX
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.BIRTHDAY
     *
     * @return the value of AU_USER.BIRTHDAY
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.BIRTHDAY
     *
     * @param birthday the value for AU_USER.BIRTHDAY
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.CARDTYPE
     *
     * @return the value of AU_USER.CARDTYPE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getCardtype() {
        return cardtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.CARDTYPE
     *
     * @param cardtype the value for AU_USER.CARDTYPE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setCardtype(String cardtype) {
        this.cardtype = cardtype == null ? null : cardtype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.CARDTYPENAME
     *
     * @return the value of AU_USER.CARDTYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getCardtypename() {
        return cardtypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.CARDTYPENAME
     *
     * @param cardtypename the value for AU_USER.CARDTYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setCardtypename(String cardtypename) {
        this.cardtypename = cardtypename == null ? null : cardtypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.IDCARD
     *
     * @return the value of AU_USER.IDCARD
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.IDCARD
     *
     * @param idcard the value for AU_USER.IDCARD
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard == null ? null : idcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.COUNTRY
     *
     * @return the value of AU_USER.COUNTRY
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.COUNTRY
     *
     * @param country the value for AU_USER.COUNTRY
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.MOBILE
     *
     * @return the value of AU_USER.MOBILE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.MOBILE
     *
     * @param mobile the value for AU_USER.MOBILE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.EMAIL
     *
     * @return the value of AU_USER.EMAIL
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.EMAIL
     *
     * @param email the value for AU_USER.EMAIL
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.USERADDRESS
     *
     * @return the value of AU_USER.USERADDRESS
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getUseraddress() {
        return useraddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.USERADDRESS
     *
     * @param useraddress the value for AU_USER.USERADDRESS
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setUseraddress(String useraddress) {
        this.useraddress = useraddress == null ? null : useraddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.POSTCODE
     *
     * @return the value of AU_USER.POSTCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.POSTCODE
     *
     * @param postcode the value for AU_USER.POSTCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.CREATETIME
     *
     * @return the value of AU_USER.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.CREATETIME
     *
     * @param createtime the value for AU_USER.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.REFERID
     *
     * @return the value of AU_USER.REFERID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public BigDecimal getReferid() {
        return referid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.REFERID
     *
     * @param referid the value for AU_USER.REFERID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setReferid(BigDecimal referid) {
        this.referid = referid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.REFERCODE
     *
     * @return the value of AU_USER.REFERCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getRefercode() {
        return refercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.REFERCODE
     *
     * @param refercode the value for AU_USER.REFERCODE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setRefercode(String refercode) {
        this.refercode = refercode == null ? null : refercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.ROLEID
     *
     * @return the value of AU_USER.ROLEID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public BigDecimal getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.ROLEID
     *
     * @param roleid the value for AU_USER.ROLEID
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setRoleid(BigDecimal roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.ROLENAME
     *
     * @return the value of AU_USER.ROLENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.ROLENAME
     *
     * @param rolename the value for AU_USER.ROLENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setRolename(String rolename) {
        this.rolename = rolename == null ? null : rolename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.USERTYPE
     *
     * @return the value of AU_USER.USERTYPE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getUsertype() {
        return usertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.USERTYPE
     *
     * @param usertype the value for AU_USER.USERTYPE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setUsertype(String usertype) {
        this.usertype = usertype == null ? null : usertype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.USERTYPENAME
     *
     * @return the value of AU_USER.USERTYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getUsertypename() {
        return usertypename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.USERTYPENAME
     *
     * @param usertypename the value for AU_USER.USERTYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setUsertypename(String usertypename) {
        this.usertypename = usertypename == null ? null : usertypename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.ISSTART
     *
     * @return the value of AU_USER.ISSTART
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public Long getIsstart() {
        return isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.ISSTART
     *
     * @param isstart the value for AU_USER.ISSTART
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setIsstart(Long isstart) {
        this.isstart = isstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.LASTUPDATE
     *
     * @return the value of AU_USER.LASTUPDATE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.LASTUPDATE
     *
     * @param lastupdate the value for AU_USER.LASTUPDATE
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.LASTLOGNUMBERIME
     *
     * @return the value of AU_USER.LASTLOGNUMBERIME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public Date getLastlognumberime() {
        return lastlognumberime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.LASTLOGNUMBERIME
     *
     * @param lastlognumberime the value for AU_USER.LASTLOGNUMBERIME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setLastlognumberime(Date lastlognumberime) {
        this.lastlognumberime = lastlognumberime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.BANKACCOUNT
     *
     * @return the value of AU_USER.BANKACCOUNT
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getBankaccount() {
        return bankaccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.BANKACCOUNT
     *
     * @param bankaccount the value for AU_USER.BANKACCOUNT
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setBankaccount(String bankaccount) {
        this.bankaccount = bankaccount == null ? null : bankaccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.BANKNAME
     *
     * @return the value of AU_USER.BANKNAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getBankname() {
        return bankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.BANKNAME
     *
     * @param bankname the value for AU_USER.BANKNAME
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setBankname(String bankname) {
        this.bankname = bankname == null ? null : bankname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.ACCOUNTHOLDER
     *
     * @return the value of AU_USER.ACCOUNTHOLDER
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getAccountholder() {
        return accountholder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.ACCOUNTHOLDER
     *
     * @param accountholder the value for AU_USER.ACCOUNTHOLDER
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setAccountholder(String accountholder) {
        this.accountholder = accountholder == null ? null : accountholder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.IDCARDPICPATH
     *
     * @return the value of AU_USER.IDCARDPICPATH
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getIdcardpicpath() {
        return idcardpicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.IDCARDPICPATH
     *
     * @param idcardpicpath the value for AU_USER.IDCARDPICPATH
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setIdcardpicpath(String idcardpicpath) {
        this.idcardpicpath = idcardpicpath == null ? null : idcardpicpath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AU_USER.BANKPICPATH
     *
     * @return the value of AU_USER.BANKPICPATH
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public String getBankpicpath() {
        return bankpicpath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AU_USER.BANKPICPATH
     *
     * @param bankpicpath the value for AU_USER.BANKPICPATH
     *
     * @mbggenerated Tue Jul 07 18:46:31 CST 2020
     */
    public void setBankpicpath(String bankpicpath) {
        this.bankpicpath = bankpicpath == null ? null : bankpicpath.trim();
    }
}