package com.newer.hysc.data.entity;

import java.math.BigDecimal;

public class DataDictionary {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_DICTIONARY.ID
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_DICTIONARY.TYPECODE
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    private String typecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_DICTIONARY.TYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_DICTIONARY.VALUEID
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    private BigDecimal valueid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DATA_DICTIONARY.VALUENAME
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    private String valuename;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_DICTIONARY.ID
     *
     * @return the value of DATA_DICTIONARY.ID
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_DICTIONARY.ID
     *
     * @param id the value for DATA_DICTIONARY.ID
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_DICTIONARY.TYPECODE
     *
     * @return the value of DATA_DICTIONARY.TYPECODE
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public String getTypecode() {
        return typecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_DICTIONARY.TYPECODE
     *
     * @param typecode the value for DATA_DICTIONARY.TYPECODE
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public void setTypecode(String typecode) {
        this.typecode = typecode == null ? null : typecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_DICTIONARY.TYPENAME
     *
     * @return the value of DATA_DICTIONARY.TYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_DICTIONARY.TYPENAME
     *
     * @param typename the value for DATA_DICTIONARY.TYPENAME
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_DICTIONARY.VALUEID
     *
     * @return the value of DATA_DICTIONARY.VALUEID
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public BigDecimal getValueid() {
        return valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_DICTIONARY.VALUEID
     *
     * @param valueid the value for DATA_DICTIONARY.VALUEID
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public void setValueid(BigDecimal valueid) {
        this.valueid = valueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DATA_DICTIONARY.VALUENAME
     *
     * @return the value of DATA_DICTIONARY.VALUENAME
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public String getValuename() {
        return valuename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DATA_DICTIONARY.VALUENAME
     *
     * @param valuename the value for DATA_DICTIONARY.VALUENAME
     *
     * @mbggenerated Tue Jul 07 18:46:51 CST 2020
     */
    public void setValuename(String valuename) {
        this.valuename = valuename == null ? null : valuename.trim();
    }
}