package com.newer.hysc.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class GoodsInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.ID
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.GOODSSN
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private String goodssn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.GOODSNAME
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private String goodsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.GOODSFORMAT
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private String goodsformat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.MARKETPRICE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private BigDecimal marketprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.REALPRICE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private BigDecimal realprice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private Long state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.NOTE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.NUM
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private BigDecimal num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.UNIT
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private String unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.LASTUPDATE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private Date lastupdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column GOODS_INFO.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    private String createdby;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.ID
     *
     * @return the value of GOODS_INFO.ID
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.ID
     *
     * @param id the value for GOODS_INFO.ID
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.GOODSSN
     *
     * @return the value of GOODS_INFO.GOODSSN
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public String getGoodssn() {
        return goodssn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.GOODSSN
     *
     * @param goodssn the value for GOODS_INFO.GOODSSN
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setGoodssn(String goodssn) {
        this.goodssn = goodssn == null ? null : goodssn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.GOODSNAME
     *
     * @return the value of GOODS_INFO.GOODSNAME
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public String getGoodsname() {
        return goodsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.GOODSNAME
     *
     * @param goodsname the value for GOODS_INFO.GOODSNAME
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setGoodsname(String goodsname) {
        this.goodsname = goodsname == null ? null : goodsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.GOODSFORMAT
     *
     * @return the value of GOODS_INFO.GOODSFORMAT
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public String getGoodsformat() {
        return goodsformat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.GOODSFORMAT
     *
     * @param goodsformat the value for GOODS_INFO.GOODSFORMAT
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setGoodsformat(String goodsformat) {
        this.goodsformat = goodsformat == null ? null : goodsformat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.MARKETPRICE
     *
     * @return the value of GOODS_INFO.MARKETPRICE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public BigDecimal getMarketprice() {
        return marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.MARKETPRICE
     *
     * @param marketprice the value for GOODS_INFO.MARKETPRICE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setMarketprice(BigDecimal marketprice) {
        this.marketprice = marketprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.REALPRICE
     *
     * @return the value of GOODS_INFO.REALPRICE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public BigDecimal getRealprice() {
        return realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.REALPRICE
     *
     * @param realprice the value for GOODS_INFO.REALPRICE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setRealprice(BigDecimal realprice) {
        this.realprice = realprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.STATE
     *
     * @return the value of GOODS_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public Long getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.STATE
     *
     * @param state the value for GOODS_INFO.STATE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setState(Long state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.NOTE
     *
     * @return the value of GOODS_INFO.NOTE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.NOTE
     *
     * @param note the value for GOODS_INFO.NOTE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.NUM
     *
     * @return the value of GOODS_INFO.NUM
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.NUM
     *
     * @param num the value for GOODS_INFO.NUM
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.UNIT
     *
     * @return the value of GOODS_INFO.UNIT
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.UNIT
     *
     * @param unit the value for GOODS_INFO.UNIT
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.CREATETIME
     *
     * @return the value of GOODS_INFO.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.CREATETIME
     *
     * @param createtime the value for GOODS_INFO.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.LASTUPDATE
     *
     * @return the value of GOODS_INFO.LASTUPDATE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public Date getLastupdate() {
        return lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.LASTUPDATE
     *
     * @param lastupdate the value for GOODS_INFO.LASTUPDATE
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setLastupdate(Date lastupdate) {
        this.lastupdate = lastupdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column GOODS_INFO.CREATEDBY
     *
     * @return the value of GOODS_INFO.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column GOODS_INFO.CREATEDBY
     *
     * @param createdby the value for GOODS_INFO.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:47:09 CST 2020
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }
}