package com.newer.hysc.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Information {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.ID
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.TITLE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.CONTENT
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.STATE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private BigDecimal state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.PUBLISHER
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private String publisher;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.PUBLISHTIME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private Date publishtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.TYPEID
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private Long typeid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.TYPENAME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private String typename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.FILENAME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private String filename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.FILEPATH
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private String filepath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.FILESIZE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private BigDecimal filesize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INFORMATION.UPLOADTIME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    private Date uploadtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.ID
     *
     * @return the value of INFORMATION.ID
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.ID
     *
     * @param id the value for INFORMATION.ID
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.TITLE
     *
     * @return the value of INFORMATION.TITLE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.TITLE
     *
     * @param title the value for INFORMATION.TITLE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.CONTENT
     *
     * @return the value of INFORMATION.CONTENT
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.CONTENT
     *
     * @param content the value for INFORMATION.CONTENT
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.STATE
     *
     * @return the value of INFORMATION.STATE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public BigDecimal getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.STATE
     *
     * @param state the value for INFORMATION.STATE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setState(BigDecimal state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.PUBLISHER
     *
     * @return the value of INFORMATION.PUBLISHER
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.PUBLISHER
     *
     * @param publisher the value for INFORMATION.PUBLISHER
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.PUBLISHTIME
     *
     * @return the value of INFORMATION.PUBLISHTIME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public Date getPublishtime() {
        return publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.PUBLISHTIME
     *
     * @param publishtime the value for INFORMATION.PUBLISHTIME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setPublishtime(Date publishtime) {
        this.publishtime = publishtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.TYPEID
     *
     * @return the value of INFORMATION.TYPEID
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public Long getTypeid() {
        return typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.TYPEID
     *
     * @param typeid the value for INFORMATION.TYPEID
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setTypeid(Long typeid) {
        this.typeid = typeid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.TYPENAME
     *
     * @return the value of INFORMATION.TYPENAME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public String getTypename() {
        return typename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.TYPENAME
     *
     * @param typename the value for INFORMATION.TYPENAME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setTypename(String typename) {
        this.typename = typename == null ? null : typename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.FILENAME
     *
     * @return the value of INFORMATION.FILENAME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public String getFilename() {
        return filename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.FILENAME
     *
     * @param filename the value for INFORMATION.FILENAME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setFilename(String filename) {
        this.filename = filename == null ? null : filename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.FILEPATH
     *
     * @return the value of INFORMATION.FILEPATH
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public String getFilepath() {
        return filepath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.FILEPATH
     *
     * @param filepath the value for INFORMATION.FILEPATH
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setFilepath(String filepath) {
        this.filepath = filepath == null ? null : filepath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.FILESIZE
     *
     * @return the value of INFORMATION.FILESIZE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public BigDecimal getFilesize() {
        return filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.FILESIZE
     *
     * @param filesize the value for INFORMATION.FILESIZE
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setFilesize(BigDecimal filesize) {
        this.filesize = filesize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INFORMATION.UPLOADTIME
     *
     * @return the value of INFORMATION.UPLOADTIME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public Date getUploadtime() {
        return uploadtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INFORMATION.UPLOADTIME
     *
     * @param uploadtime the value for INFORMATION.UPLOADTIME
     *
     * @mbggenerated Tue Jul 07 18:48:04 CST 2020
     */
    public void setUploadtime(Date uploadtime) {
        this.uploadtime = uploadtime;
    }
}