package com.newer.hysc.data.entity;

public class MultiLan {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.ELEMENT_ID
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String elementId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.PAGE_PATH
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String pagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.SCN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String scn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.TCN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String tcn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.EN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String en;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.JP
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String jp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.KR
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String kr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.FR
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String fr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MULTI_LAN.RA
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    private String ra;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.ELEMENT_ID
     *
     * @return the value of MULTI_LAN.ELEMENT_ID
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getElementId() {
        return elementId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.ELEMENT_ID
     *
     * @param elementId the value for MULTI_LAN.ELEMENT_ID
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setElementId(String elementId) {
        this.elementId = elementId == null ? null : elementId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.PAGE_PATH
     *
     * @return the value of MULTI_LAN.PAGE_PATH
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getPagePath() {
        return pagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.PAGE_PATH
     *
     * @param pagePath the value for MULTI_LAN.PAGE_PATH
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setPagePath(String pagePath) {
        this.pagePath = pagePath == null ? null : pagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.SCN
     *
     * @return the value of MULTI_LAN.SCN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getScn() {
        return scn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.SCN
     *
     * @param scn the value for MULTI_LAN.SCN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setScn(String scn) {
        this.scn = scn == null ? null : scn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.TCN
     *
     * @return the value of MULTI_LAN.TCN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getTcn() {
        return tcn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.TCN
     *
     * @param tcn the value for MULTI_LAN.TCN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setTcn(String tcn) {
        this.tcn = tcn == null ? null : tcn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.EN
     *
     * @return the value of MULTI_LAN.EN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getEn() {
        return en;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.EN
     *
     * @param en the value for MULTI_LAN.EN
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setEn(String en) {
        this.en = en == null ? null : en.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.JP
     *
     * @return the value of MULTI_LAN.JP
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getJp() {
        return jp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.JP
     *
     * @param jp the value for MULTI_LAN.JP
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setJp(String jp) {
        this.jp = jp == null ? null : jp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.KR
     *
     * @return the value of MULTI_LAN.KR
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getKr() {
        return kr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.KR
     *
     * @param kr the value for MULTI_LAN.KR
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setKr(String kr) {
        this.kr = kr == null ? null : kr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.FR
     *
     * @return the value of MULTI_LAN.FR
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getFr() {
        return fr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.FR
     *
     * @param fr the value for MULTI_LAN.FR
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setFr(String fr) {
        this.fr = fr == null ? null : fr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column MULTI_LAN.RA
     *
     * @return the value of MULTI_LAN.RA
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public String getRa() {
        return ra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column MULTI_LAN.RA
     *
     * @param ra the value for MULTI_LAN.RA
     *
     * @mbggenerated Tue Jul 07 18:38:23 CST 2020
     */
    public void setRa(String ra) {
        this.ra = ra == null ? null : ra.trim();
    }
}