package com.newer.hysc.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class Reply {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.ID
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.MESSAGEID
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    private BigDecimal messageid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.REPLYCONTENT
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    private String replycontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    private String createdby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column REPLY.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.ID
     *
     * @return the value of REPLY.ID
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.ID
     *
     * @param id the value for REPLY.ID
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.MESSAGEID
     *
     * @return the value of REPLY.MESSAGEID
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public BigDecimal getMessageid() {
        return messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.MESSAGEID
     *
     * @param messageid the value for REPLY.MESSAGEID
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public void setMessageid(BigDecimal messageid) {
        this.messageid = messageid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.REPLYCONTENT
     *
     * @return the value of REPLY.REPLYCONTENT
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public String getReplycontent() {
        return replycontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.REPLYCONTENT
     *
     * @param replycontent the value for REPLY.REPLYCONTENT
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public void setReplycontent(String replycontent) {
        this.replycontent = replycontent == null ? null : replycontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.CREATEDBY
     *
     * @return the value of REPLY.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public String getCreatedby() {
        return createdby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.CREATEDBY
     *
     * @param createdby the value for REPLY.CREATEDBY
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public void setCreatedby(String createdby) {
        this.createdby = createdby == null ? null : createdby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column REPLY.CREATETIME
     *
     * @return the value of REPLY.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column REPLY.CREATETIME
     *
     * @param createtime the value for REPLY.CREATETIME
     *
     * @mbggenerated Tue Jul 07 18:48:37 CST 2020
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}