package com.newer.hysc.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserPair201312 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.PAIR_ID
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private String pairId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.MYDATE
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private Date mydate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.BONUS_USER_ID
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private String bonusUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.LEFT_USER
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private Integer leftUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.RIGHT_USER
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private Integer rightUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.LEFT_KEEP
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private Integer leftKeep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.RIGHT_KEEP
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private Integer rightKeep;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.EACH_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private BigDecimal eachPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.SUM_PAIR_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private BigDecimal sumPairPv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.BONUS_RATE
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private BigDecimal bonusRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_PAIR_201312.BONUS_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    private BigDecimal bonusPv;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.PAIR_ID
     *
     * @return the value of USER_PAIR_201312.PAIR_ID
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public String getPairId() {
        return pairId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.PAIR_ID
     *
     * @param pairId the value for USER_PAIR_201312.PAIR_ID
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setPairId(String pairId) {
        this.pairId = pairId == null ? null : pairId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.MYDATE
     *
     * @return the value of USER_PAIR_201312.MYDATE
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public Date getMydate() {
        return mydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.MYDATE
     *
     * @param mydate the value for USER_PAIR_201312.MYDATE
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setMydate(Date mydate) {
        this.mydate = mydate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.BONUS_USER_ID
     *
     * @return the value of USER_PAIR_201312.BONUS_USER_ID
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public String getBonusUserId() {
        return bonusUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.BONUS_USER_ID
     *
     * @param bonusUserId the value for USER_PAIR_201312.BONUS_USER_ID
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setBonusUserId(String bonusUserId) {
        this.bonusUserId = bonusUserId == null ? null : bonusUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.LEFT_USER
     *
     * @return the value of USER_PAIR_201312.LEFT_USER
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public Integer getLeftUser() {
        return leftUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.LEFT_USER
     *
     * @param leftUser the value for USER_PAIR_201312.LEFT_USER
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setLeftUser(Integer leftUser) {
        this.leftUser = leftUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.RIGHT_USER
     *
     * @return the value of USER_PAIR_201312.RIGHT_USER
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public Integer getRightUser() {
        return rightUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.RIGHT_USER
     *
     * @param rightUser the value for USER_PAIR_201312.RIGHT_USER
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setRightUser(Integer rightUser) {
        this.rightUser = rightUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.LEFT_KEEP
     *
     * @return the value of USER_PAIR_201312.LEFT_KEEP
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public Integer getLeftKeep() {
        return leftKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.LEFT_KEEP
     *
     * @param leftKeep the value for USER_PAIR_201312.LEFT_KEEP
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setLeftKeep(Integer leftKeep) {
        this.leftKeep = leftKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.RIGHT_KEEP
     *
     * @return the value of USER_PAIR_201312.RIGHT_KEEP
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public Integer getRightKeep() {
        return rightKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.RIGHT_KEEP
     *
     * @param rightKeep the value for USER_PAIR_201312.RIGHT_KEEP
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setRightKeep(Integer rightKeep) {
        this.rightKeep = rightKeep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.EACH_PV
     *
     * @return the value of USER_PAIR_201312.EACH_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public BigDecimal getEachPv() {
        return eachPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.EACH_PV
     *
     * @param eachPv the value for USER_PAIR_201312.EACH_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setEachPv(BigDecimal eachPv) {
        this.eachPv = eachPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.SUM_PAIR_PV
     *
     * @return the value of USER_PAIR_201312.SUM_PAIR_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public BigDecimal getSumPairPv() {
        return sumPairPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.SUM_PAIR_PV
     *
     * @param sumPairPv the value for USER_PAIR_201312.SUM_PAIR_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setSumPairPv(BigDecimal sumPairPv) {
        this.sumPairPv = sumPairPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.BONUS_RATE
     *
     * @return the value of USER_PAIR_201312.BONUS_RATE
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public BigDecimal getBonusRate() {
        return bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.BONUS_RATE
     *
     * @param bonusRate the value for USER_PAIR_201312.BONUS_RATE
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setBonusRate(BigDecimal bonusRate) {
        this.bonusRate = bonusRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_PAIR_201312.BONUS_PV
     *
     * @return the value of USER_PAIR_201312.BONUS_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public BigDecimal getBonusPv() {
        return bonusPv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_PAIR_201312.BONUS_PV
     *
     * @param bonusPv the value for USER_PAIR_201312.BONUS_PV
     *
     * @mbggenerated Tue Jul 07 18:42:58 CST 2020
     */
    public void setBonusPv(BigDecimal bonusPv) {
        this.bonusPv = bonusPv;
    }
}