package com.newer.hysc.data.entity;

import java.math.BigDecimal;
import java.util.Date;

public class UserRecharge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.RECHARGE_ID
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String rechargeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.RECHARGE_TIME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private Date rechargeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.RECHARGE_NUM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String rechargeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.USER_ID
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.CURRENCY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String currency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.RECHARGE_MONEY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private BigDecimal rechargeMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.NOTE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.CREDITED_MONEY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private BigDecimal creditedMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.CREDITED_TIME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private Date creditedTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.AUDIT_USER
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String auditUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.PV_RATE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private BigDecimal pvRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.PV
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private BigDecimal pv;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.BANK_NAME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.BANK_ACCOUNT
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.PLATFORM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String platform;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_RECHARGE.PARAM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    private String param;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.RECHARGE_ID
     *
     * @return the value of USER_RECHARGE.RECHARGE_ID
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getRechargeId() {
        return rechargeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.RECHARGE_ID
     *
     * @param rechargeId the value for USER_RECHARGE.RECHARGE_ID
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setRechargeId(String rechargeId) {
        this.rechargeId = rechargeId == null ? null : rechargeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.RECHARGE_TIME
     *
     * @return the value of USER_RECHARGE.RECHARGE_TIME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public Date getRechargeTime() {
        return rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.RECHARGE_TIME
     *
     * @param rechargeTime the value for USER_RECHARGE.RECHARGE_TIME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setRechargeTime(Date rechargeTime) {
        this.rechargeTime = rechargeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.RECHARGE_NUM
     *
     * @return the value of USER_RECHARGE.RECHARGE_NUM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getRechargeNum() {
        return rechargeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.RECHARGE_NUM
     *
     * @param rechargeNum the value for USER_RECHARGE.RECHARGE_NUM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setRechargeNum(String rechargeNum) {
        this.rechargeNum = rechargeNum == null ? null : rechargeNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.USER_ID
     *
     * @return the value of USER_RECHARGE.USER_ID
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.USER_ID
     *
     * @param userId the value for USER_RECHARGE.USER_ID
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.CURRENCY
     *
     * @return the value of USER_RECHARGE.CURRENCY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getCurrency() {
        return currency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.CURRENCY
     *
     * @param currency the value for USER_RECHARGE.CURRENCY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setCurrency(String currency) {
        this.currency = currency == null ? null : currency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.RECHARGE_MONEY
     *
     * @return the value of USER_RECHARGE.RECHARGE_MONEY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public BigDecimal getRechargeMoney() {
        return rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.RECHARGE_MONEY
     *
     * @param rechargeMoney the value for USER_RECHARGE.RECHARGE_MONEY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setRechargeMoney(BigDecimal rechargeMoney) {
        this.rechargeMoney = rechargeMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.NOTE
     *
     * @return the value of USER_RECHARGE.NOTE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.NOTE
     *
     * @param note the value for USER_RECHARGE.NOTE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.CREDITED_MONEY
     *
     * @return the value of USER_RECHARGE.CREDITED_MONEY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public BigDecimal getCreditedMoney() {
        return creditedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.CREDITED_MONEY
     *
     * @param creditedMoney the value for USER_RECHARGE.CREDITED_MONEY
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setCreditedMoney(BigDecimal creditedMoney) {
        this.creditedMoney = creditedMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.CREDITED_TIME
     *
     * @return the value of USER_RECHARGE.CREDITED_TIME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public Date getCreditedTime() {
        return creditedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.CREDITED_TIME
     *
     * @param creditedTime the value for USER_RECHARGE.CREDITED_TIME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setCreditedTime(Date creditedTime) {
        this.creditedTime = creditedTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.AUDIT_USER
     *
     * @return the value of USER_RECHARGE.AUDIT_USER
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getAuditUser() {
        return auditUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.AUDIT_USER
     *
     * @param auditUser the value for USER_RECHARGE.AUDIT_USER
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setAuditUser(String auditUser) {
        this.auditUser = auditUser == null ? null : auditUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.PV_RATE
     *
     * @return the value of USER_RECHARGE.PV_RATE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public BigDecimal getPvRate() {
        return pvRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.PV_RATE
     *
     * @param pvRate the value for USER_RECHARGE.PV_RATE
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setPvRate(BigDecimal pvRate) {
        this.pvRate = pvRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.PV
     *
     * @return the value of USER_RECHARGE.PV
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public BigDecimal getPv() {
        return pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.PV
     *
     * @param pv the value for USER_RECHARGE.PV
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setPv(BigDecimal pv) {
        this.pv = pv;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.BANK_NAME
     *
     * @return the value of USER_RECHARGE.BANK_NAME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.BANK_NAME
     *
     * @param bankName the value for USER_RECHARGE.BANK_NAME
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.BANK_ACCOUNT
     *
     * @return the value of USER_RECHARGE.BANK_ACCOUNT
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.BANK_ACCOUNT
     *
     * @param bankAccount the value for USER_RECHARGE.BANK_ACCOUNT
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.PLATFORM
     *
     * @return the value of USER_RECHARGE.PLATFORM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getPlatform() {
        return platform;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.PLATFORM
     *
     * @param platform the value for USER_RECHARGE.PLATFORM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setPlatform(String platform) {
        this.platform = platform == null ? null : platform.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_RECHARGE.PARAM
     *
     * @return the value of USER_RECHARGE.PARAM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public String getParam() {
        return param;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_RECHARGE.PARAM
     *
     * @param param the value for USER_RECHARGE.PARAM
     *
     * @mbggenerated Tue Jul 07 18:44:20 CST 2020
     */
    public void setParam(String param) {
        this.param = param == null ? null : param.trim();
    }
}