package com.newer.datang.data.dao;

import com.newer.datang.data.entity.TEmployee;
import com.newer.datang.data.entity.TEmployeeExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TEmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int countByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int deleteByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int insert(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int insertSelective(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    List<TEmployee> selectByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    TEmployee selectByPrimaryKey(BigDecimal employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") TEmployee record, @Param("example") TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByExample(@Param("record") TEmployee record, @Param("example") TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByPrimaryKeySelective(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByPrimaryKey(TEmployee record);
}