package com.newer.datang.data.dao;

import com.newer.datang.data.entity.TEmployee;
import com.newer.datang.data.entity.TEmployeeExample;

import java.math.BigDecimal;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface TEmployeeMapper {
	
	//根据主管id查到手下的所有员工+分页
	List<TEmployee> selectEmpByRarntId(Map<String, Object> map);
	
	//用户登录
	TEmployee Emplogin(Map<String, Object> map);
	
	//查询上级
	TEmployee selectByPrimaryKeyParent(BigDecimal parentId);
	
	//admin分页
		 public List<TEmployee> selectbypage(Map<String, Object> param); 
		//查询所主管
		 public List<TEmployee> queryAllManager(TEmployee id);
	
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int countByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int deleteByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int deleteByPrimaryKey(BigDecimal employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int insert(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int insertSelective(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    List<TEmployee> selectByExample(TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    TEmployee selectByPrimaryKey(BigDecimal employeeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByExampleSelective(@Param("record") TEmployee record, @Param("example") TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByExample(@Param("record") TEmployee record, @Param("example") TEmployeeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByPrimaryKeySelective(TEmployee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table T_EMPLOYEE
     *
     * @mbggenerated Wed Jul 08 19:18:17 CST 2020
     */
    int updateByPrimaryKey(TEmployee record);
}